// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHqBM_TYhzyywp-vi8pg4_dkzftFv8JL0',
    appId: '1:687714133058:web:8de22d98cefcf2a09679db',
    messagingSenderId: '687714133058',
    projectId: 'assessment-app-89e19',
    authDomain: 'assessment-app-89e19.firebaseapp.com',
    storageBucket: 'assessment-app-89e19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO87Y5zNFku1niiqbNXnqvsO9JZ1owkaQ',
    appId: '1:687714133058:android:429e0b66deac81fe9679db',
    messagingSenderId: '687714133058',
    projectId: 'assessment-app-89e19',
    storageBucket: 'assessment-app-89e19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG8CcWv4p45z3TJm4ajqlXvEbn0MQ9jh8',
    appId: '1:687714133058:ios:20d3dae888b668b19679db',
    messagingSenderId: '687714133058',
    projectId: 'assessment-app-89e19',
    storageBucket: 'assessment-app-89e19.firebasestorage.app',
    iosBundleId: 'com.example.assessmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG8CcWv4p45z3TJm4ajqlXvEbn0MQ9jh8',
    appId: '1:687714133058:ios:20d3dae888b668b19679db',
    messagingSenderId: '687714133058',
    projectId: 'assessment-app-89e19',
    storageBucket: 'assessment-app-89e19.firebasestorage.app',
    iosBundleId: 'com.example.assessmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHqBM_TYhzyywp-vi8pg4_dkzftFv8JL0',
    appId: '1:687714133058:web:2fa82cbf829471889679db',
    messagingSenderId: '687714133058',
    projectId: 'assessment-app-89e19',
    authDomain: 'assessment-app-89e19.firebaseapp.com',
    storageBucket: 'assessment-app-89e19.firebasestorage.app',
  );
}
